import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect } from 'react';
import { toast } from 'react-toastify';

const Home: NextPage = () => {

  useEffect(() => {
    readRequest();
  }, [])
  const readRequest = async () => {
    try {
      const response = await fetch('/api/login');
      const data = await response.json();
      console.log(data);
      toast.success('Get request success');
    } catch (error) {
      console.log('error on api request', error);
    }
  }
  
  const handleSignatureSend = async () => {
    try {
      const data = {
        message: 'This is a POST request',
      }
      const response2 = await fetch('/api/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      })
      const json = await response2.json()
      console.log('post info ' , json);
      toast.success('Post request success');
    } catch (error) {
      console.log('error on api request', error);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Wallet Secure Login
        </h1>

        <p className={styles.description}>
          {"Let's learn how to build a secure Web3 login system"}
        </p>

      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Eth Bogotá 2024 
        </a>
      </footer>
    </div>
  );
};

export default Home;
